// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DemoDIVsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "DemoDIVsix.9403aead-8cb4-4e12-acd8-7d2dd809dd02";
        public const string Name = "DemoDIVsix";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tony Hallett";
        public const string Tags = "";
    }
}
