// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DemoDIVsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DemoDIVsixString = "fd6625cd-80bf-49c7-abdf-01ee87176bd5";
        public static Guid DemoDIVsix = new Guid(DemoDIVsixString);

        public const string ControlsGuidString = "8d018075-99fe-4031-8c53-5ec853aefe07";
        public static Guid ControlsGuid = new Guid(ControlsGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdIdOpenToolWindow = 0x0001;
    }
}